package com.silita.notice.common;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class RegionCommon {

    public static List<Map<String, Object>> region() {
        List<Map<String,Object>> listMap = new ArrayList<>();

        Map<String, Object> map = new HashMap<>();
        map.put("name","安徽省");
        map.put("code","anh");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","北京市");
        map.put("code","beij");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","重庆市");
        map.put("code","chongq");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","福建省");
        map.put("code","fuj");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","甘肃省");
        map.put("code","gans");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","广东省");
        map.put("code","guangd");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","广西壮族自治区");
        map.put("code","guangx");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","贵州省");
        map.put("code","guiz");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","海南省");
        map.put("code","hain");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","河北省");
        map.put("code","hebei");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","黑龙江省");
        map.put("code","heilj");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","河南省");
        map.put("code","henan");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","湖北省");
        map.put("code","hubei");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","湖南省");
        map.put("code","hunan");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","江苏省");
        map.put("code","jiangs");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","江西省");
        map.put("code","jiangx");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","吉林省");
        map.put("code","jil");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","辽宁省");
        map.put("code","liaon");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","内蒙古自治区");
        map.put("code","neimg");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","宁夏回族自治区");
        map.put("code","ningx");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","青海省");
        map.put("code","qingh");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","山西省");
        map.put("code","sanx");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","山东省");
        map.put("code","shand");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","上海市");
        map.put("code","shangh");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","陕西省");
        map.put("code","shanxi");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","四川省");
        map.put("code","sichuan");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","天津市");
        map.put("code","tianj");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","新疆维吾尔自治区");
        map.put("code","xinjiang");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","西藏自治区");
        map.put("code","xizang");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","云南省");
        map.put("code","yunn");
        listMap.add(map);
        map = new HashMap<>();
        map.put("name","浙江省");
        map.put("code","zhej");


        return listMap;
    }


}
